import type { Metadata } from "next";
import { Public_Sans } from 'next/font/google';
import "./global.scss";
import React from 'react';

const fontSans = Public_Sans({
  variable: "--font-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "CitizenBand",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${fontSans.variable}`}>
        {children}
      </body>
    </html>
  );
}
